name: first_page
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  local_auth: ^2.3.0
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  file_picker: ^6.1.1
  intl: ^0.18.1 



  
  flutter_spinkit: ^5.2.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.7
  geocoding: ^2.1.0
  flutter_screenutil: ^5.9.0
  camera: ^0.11.0+2
  mapbox_gl_platform_interface: ^0.16.0

  gallery_saver: ^2.3.2
  url_launcher: ^6.1.11
  flutter_map: any
  latlong2: any
  geolocator_android: ^5.0.1+1
  google_maps_flutter: ^2.2.3
  http: ^0.13.5 
  geolocator: ^14.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  provider: ^6.0.5
  flutter_lints: ^4.0.0
  percent_indicator: ^4.2.3
  http: ^0.13.6


flutter:
  uses-material-design: true
  assets:
    
    - assets/no_reflictions.png
    - assets/not_cropped.png
    - assets/logo (4).png
    - assets/Logo (2).png
    - assets/blue_shape.png
    - assets/dark_shape.png
    - assets/shape.png
    - assets/mail.png
    - assets/investa.png
    - assets/logo (3).png
    - assets/I.png
    - assets/fakhr.png
    - assets/suc.png
    - assets/fail.png
    - assets/chatbot_icon.png
    - assets/Fashion (2).png
    - assets/Beauty (2).png
    - assets/Food Truck (2).png
    - assets/Food & Beverage.png
    - assets/bubble.png
    - assets/bubble 3.png
    - assets/bubble 2.png
    - assets/Health & Fitness.png



    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
